---
abstract: 'Because parallel requests should be as fun as parallololololol!'
author:
  - 'Magnus Holm <judofyr@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parallol
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: 0
version: 0.1
